apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      initContainers:
        - name: init-package
          image: harbor.vankeservice.com/demo/demo
          command: ["sleep"]
          args: ["infinity"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /app
              name: package
      containers:
        - name: tomcat-base
          image: harbor.vankeservice.com/rdmp/base-image
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: demo-app
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - mountPath: /usr/local/tomcat/webapps
              name: package
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: package
          emptyDir: {}

