apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  template:
    spec:
      containers:
        - name: demo-app
          env:
            - name: SVC_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: "ILOGTAIL_JMX_PORT"
              value: "9999"
            - name: "ILOGTAIL_JMX_TAGS"
              value: "$(SVC_NAME)"
            - name: JMX_OPTIONS
              value: "-Dcom.sun.management.jmxremote \
                      -Dcom.sun.management.jmxremote.authenticate=false \
                      -Dcom.sun.management.jmxremote.ssl=false \
                      -Dcom.sun.management.jmxremote.local.only=false \
                      -Dcom.sun.management.jmxremote.port=$(ILOGTAIL_JMX_PORT) \
                      -Dcom.sun.management.jmxremote.rmi.port=$(ILOGTAIL_JMX_PORT) \
                      -Djava.rmi.server.hostname=$(POD_IP)"
            - name: GC_PATH
              value: "/opt/logs/$(SVC_NAME)/$(POD_IP)"
            - name: CATALINA_OPTS
              value: "$(CATALINA_OPTS)  -Xloggc:$(GC_PATH)/$(SVC_NAME)-%p-%t.log -XX:HeapDumpPath=$(GC_PATH)/$(SVC_NAME).hprof $(JMX_OPTIONS)"
            - name: JAVA_OPTS
              value: "$(JAVA_OPTS)  -Xloggc:$(GC_PATH)/$(SVC_NAME)-%p-%t.log -XX:HeapDumpPath=$(GC_PATH)/$(SVC_NAME).hprof $(JMX_OPTIONS)"
          volumeMounts:
            - name: billcenter-nas-pvc
              mountPath: /opt/logs/
            - name: timezone
              mountPath: /etc/localtime
      volumes:
        - name: billcenter-nas-pvc
          persistentVolumeClaim:
            claimName: billcenter-nas-pvc
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
      initContainers:
        - name: init-dump-path
          image: pkg.onewo.com/plutus-docker-prod-local/apline-openjdk8:latest
          command: [ 'sh','-c','echo $GC_PATH; mkdir -p $GC_PATH' ]
          env:
            - name: SVC_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: GC_PATH
              value: "/opt/logs/$(SVC_NAME)/$(POD_IP)/"
          envFrom:
            - configMapRef:
                name: demo-app
          volumeMounts:
            - mountPath: /opt/logs/
              name: billcenter-nas-pvc