apiVersion: v1
kind: Service
metadata:
  labels:
    groups: jszt
  name: demo-app
spec:
  ports:
  - name: http
    port: 8081
    targetPort: http
  selector:
    groups: jszt 
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
